# Generated by Django 4.0.3 on 2022-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rating_andcomments_minus_rating_andcomments_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_andcomments',
            name='using_exp',
            field=models.TextField(null=True, verbose_name='Опыт использования'),
        ),
        migrations.AlterField(
            model_name='rating_andcomments',
            name='minus',
            field=models.TextField(null=True, verbose_name='Минусы товара'),
        ),
        migrations.AlterField(
            model_name='rating_andcomments',
            name='plus',
            field=models.TextField(null=True, verbose_name='Плюсы товара'),
        ),
    ]
